global:
  checkNewVersion: true
  sendAnonymousUsage: false

providers:
  file:
    watch: true
    directory: /etc/traefik/conf.d

api:
  dashboard: true
  insecure: false

log:
  level: DEBUG # <DEBUG | INFO* | WARN | ERROR | FATAL | PANIC>
  format: common # <common* | json>

accessLog:
  format: common # <common* | json>

entrypoints:
  web:
    address: :80
  websecure:
    address: :443
